<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.8.3 on win32)" generated="20240523 11:09:18.529" rpa="false">
<suite id="s1" name="Suites">
<suite id="s1-s1" name="ClaimIntegratedSub" source="C:\Users\AGebril\PycharmProjects\QC_Automation_Claim\Tests\ClaimIntegratedSub.robot">
<test id="s1-s1-t1" name="${Testcase id} ${Type} ${Desc}">
<status status="FAIL" starttime="20240523 11:09:19.009" endtime="20240523 11:09:19.011" critical="yes">Test case contains no keywords.</status>
</test>
<doc>Suite description</doc>
<status status="FAIL" starttime="20240523 11:09:18.553" endtime="20240523 11:09:19.012"></status>
</suite>
<status status="FAIL" starttime="20240523 11:09:18.539" endtime="20240523 11:09:19.013"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Suites">Suites</stat>
<stat pass="0" fail="1" id="s1-s1" name="ClaimIntegratedSub">Suites.ClaimIntegratedSub</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20240523 11:09:18.978" level="ERROR">Error in file 'C:\Users\AGebril\PycharmProjects\QC_Automation_Claim\Tests\ClaimIntegratedSub.robot' on line 11: Resource file '..\Resources\Keyword\CliamSub.robot' does not exist.</msg>
<msg timestamp="20240523 11:09:18.992" level="ERROR">Error in file 'C:\Users\AGebril\PycharmProjects\QC_Automation_Claim\Tests\ClaimIntegratedSub.robot' on line 14: Resource file '..\Keyword\CliamSub.robot' does not exist.</msg>
<msg timestamp="20240523 11:09:18.993" level="ERROR">[ DataDriver ] Error in robot file:
  File "C:\Users\AGebril\PycharmProjects\QC_Automation_Claim\Tests\ClaimIntegratedSub.robot", line 0</msg>
<msg timestamp="20240523 11:09:18.994" level="ERROR">In source file:
  File "../Resources/DataDriven/ClaimSubmissionIntegrated.xlsx", line 0</msg>
<msg timestamp="20240523 11:09:18.995" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: FileNotFoundError: File attribute was not a full path. Tried to find C:\Users\AGebril\PycharmProjects\QC_Automation_Claim\Tests\../Resources/DataDriven/ClaimSubmissionIntegrated.xlsx but file does not exist.</msg>
</errors>
</robot>
